import { StyleSheet } from "react-native";
import { colors, radii, spacing, typography } from "../theme/tokens";

export const homeStyles = StyleSheet.create({
  page: {
    flexGrow: 1,
    backgroundColor: colors.background,
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.md,
    alignItems: "center",
  },
  shell: {
    width: "100%",
    maxWidth: 960,
    gap: spacing.lg,
  },
  heroCard: {
    backgroundColor: colors.primaryDark,
    borderRadius: radii.lg,
    padding: spacing.lg,
    gap: spacing.md,
  },
  heroEyebrow: {
    color: colors.accent,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    fontSize: 12,
    fontWeight: "700",
  },
  heroTitle: {
    color: colors.textOnPrimary,
    fontSize: 30,
    lineHeight: 36,
    fontWeight: "700",
  },
  heroCopy: {
    color: "rgba(255,255,255,0.86)",
    fontSize: 15,
    lineHeight: 22,
  },
  logoRow: {
    marginBottom: spacing.xs,
    alignSelf: "flex-start",
  },
  statRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  statCard: {
    flexGrow: 1,
    flexBasis: 160,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    padding: spacing.md,
    gap: 2,
  },
  statLabel: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  statValue: {
    color: colors.textOnPrimary,
    fontSize: 15,
    fontWeight: "600",
  },
  workspaceCard: {
    width: "100%",
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    gap: spacing.md,
  },
  workspaceFrame: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.sm,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
  },
  sectionTitle: {
    ...typography.label,
    color: colors.textPrimary,
  },
  actionStack: {
    gap: spacing.xs,
  },
  loading: {
    marginVertical: spacing.sm,
  },
  preview: {
    width: "100%",
    maxWidth: 500,
    alignSelf: "center",
    aspectRatio: 1,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceMuted,
  },
  emptyPreview: {
    width: "100%",
    maxWidth: 500,
    aspectRatio: 1,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    padding: spacing.lg,
    gap: spacing.xs,
  },
  emptyPreviewTitle: {
    ...typography.label,
    color: colors.textPrimary,
  },
  emptyPreviewCopy: {
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: 20,
  },
  resultBox: {
    marginTop: spacing.sm,
    padding: spacing.lg,
    borderRadius: radii.lg,
    backgroundColor: colors.successBg,
    width: "100%",
    gap: spacing.xs,
  },
  resultLabel: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  resultConfidence: {
    color: colors.success,
    fontSize: 14,
    fontWeight: "600",
  },
  resultRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  breakdownTitle: {
    marginTop: spacing.sm,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  resultName: {
    color: colors.textPrimary,
  },
  resultScore: {
    color: colors.textSecondary,
    fontWeight: "600",
  },
  errorBox: {
    marginTop: spacing.sm,
    padding: spacing.lg,
    borderRadius: radii.lg,
    backgroundColor: colors.errorBg,
    width: "100%",
  },
  errorText: {
    color: colors.error,
  },
  disclaimerBox: {
    marginTop: spacing.xs,
    paddingHorizontal: spacing.md,
  },
  disclaimerText: {
    fontSize: 12,
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: 18,
  },
});
